# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 17:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20171126_1647'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Course',
        ),
    ]
