# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-10 22:28
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=30, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[\\w.@+-]+$', 32), 'Este campo apenas pode conter letras, digitos ou @/.+/-/_', 'invalid')], verbose_name='Nome do Usuário'),
        ),
    ]
